In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
import re
style.use('fast')

header_list = ["Cause Gene", "Effect Gene", "mean_importance"]
experiment_ID = "lbd29_21h_6t_RNAseq"

genes_info = pd.read_csv("C:/Users/ivana/OneDrive/Desktop/Internship New Folder/Analysis Experimental Data/genes_info.tsv", sep = "\t")
genes_name = pd.DataFrame(columns = ["regulator-target","regulator-target_names"])
# Noncoding genes:
noncoding_genes = genes_info["gene_name"].iloc[145:].values.tolist()

k = 0
for i in range(len(genes_info)):
    for j in range(len(genes_info)):
        if genes_info["gene_id"].iloc[i] != genes_info["gene_id"].iloc[j]:
    
            genes_name.loc[k] = [f"('{genes_info['gene_id'].iloc[i]}','{genes_info['gene_id'].iloc[j]}')", f"('{genes_info['gene_name'].iloc[i]}','{genes_info['gene_name'].iloc[j]}')"]
            k = k+1

genes_name = genes_name.sort_values(by = ["regulator-target"])

In [2]:
ranking_SWING_DataFrame = pd.DataFrame()
ranking_dynGENIE3_DataFrame = pd.DataFrame()

ranking_SWING_rand_DataFrame = pd.DataFrame()
ranking_dynGENIE3_rand_DataFrame = pd.DataFrame()

ranking_SWING_crand_DataFrame = pd.DataFrame()
ranking_dynGENIE3_crand_DataFrame = pd.DataFrame()
    
end = 0
    
for j in range(100):
    
    first = end + 1
    end = end + 10
    
    ranking_dynGENIE3 = pd.read_csv(f"C:/Users/ivana/OneDrive/Desktop/Internship New Folder/Analysis Experimental Data/Results_instances-1000/Results_dynGENIE3_{experiment_ID}_genes-157/Mean_Importance_{experiment_ID}/ranking_dynGENIE3_{experiment_ID}_range{first}-{end}.txt", sep = "\t",names = header_list).sort_values(by=["Cause Gene", "Effect Gene"])
    ranking_dynGENIE3_rand = pd.read_csv(f"C:/Users/ivana/OneDrive/Desktop/Internship New Folder/Analysis Experimental Data/Results_instances-1000/Results_dynGENIE3_{experiment_ID}_genes-157/Mean_Importance_{experiment_ID}_rand/ranking_dynGENIE3_rand_{experiment_ID}_range{first}-{end}.txt", sep = "\t",names = header_list).sort_values(by=["Cause Gene", "Effect Gene"])
    ranking_dynGENIE3_crand = pd.read_csv(f"C:/Users/ivana/OneDrive/Desktop/Internship New Folder/Analysis Experimental Data/Results_instances-1000/Results_dynGENIE3_{experiment_ID}_genes-157/Mean_Importance_{experiment_ID}_crand/ranking_dynGENIE3_crand_{experiment_ID}_range{first}-{end}.txt", sep = "\t",names = header_list).sort_values(by=["Cause Gene", "Effect Gene"])
                          
    ranking_dynGENIE3_DataFrame[f"ranking_dynGENIE3_DataFrame_{first}_{end}"] = ranking_dynGENIE3["mean_importance"].values.tolist()
    ranking_dynGENIE3_rand_DataFrame[f"ranking_dynGENIE3_rand_DataFrame_{first}_{end}"] = ranking_dynGENIE3_rand["mean_importance"].values.tolist()
    ranking_dynGENIE3_crand_DataFrame[f"ranking_dynGENIE3_crand_DataFrame_{first}_{end}"] = ranking_dynGENIE3_crand["mean_importance"].values.tolist()
    
    ranking_SWING = pd.read_csv(f"C:/Users/ivana/OneDrive/Desktop/Internship New Folder/Analysis Experimental Data/Results_instances-1000/Results_SWING_{experiment_ID}_genes-157/Mean_Importance_{experiment_ID}/ranking_SWING_{experiment_ID}_range{first}-{end}.txt", sep = "\t").sort_values(by=["regulator-target"])
    ranking_SWING_DataFrame[f"ranking_SWING_DataFrame_{first}_{end}"] = ranking_SWING["mean_importance"].values.tolist()
    
    ranking_SWING_rand = pd.read_csv(f"C:/Users/ivana/OneDrive/Desktop/Internship New Folder/Analysis Experimental Data/Results_instances-1000/Results_SWING_{experiment_ID}_genes-157/Mean_Importance_{experiment_ID}_rand/ranking_SWING_rand_{experiment_ID}_range{first}-{end}.txt", sep = "\t").sort_values(by=["regulator-target"])
    ranking_SWING_rand_DataFrame[f"ranking_SWING_DataFrame_{first}_{end}_rand"] = ranking_SWING_rand["mean_importance"].values.tolist()
    
    ranking_SWING_crand = pd.read_csv(f"C:/Users/ivana/OneDrive/Desktop/Internship New Folder/Analysis Experimental Data/Results_instances-1000/Results_SWING_{experiment_ID}_genes-157/Mean_Importance_{experiment_ID}_crand/ranking_SWING_crand_{experiment_ID}_range{first}-{end}.txt", sep = "\t").sort_values(by=["regulator-target"])
    ranking_SWING_crand_DataFrame[f"ranking_SWING_DataFrame_{first}_{end}_crand"] = ranking_SWING_crand["mean_importance"].values.tolist()
    
    
ranking_SWING_mean = pd.DataFrame()
ranking_dynGENIE3_mean = pd.DataFrame()

ranking_SWING_rand_mean = pd.DataFrame()
ranking_dynGENIE3_rand_mean = pd.DataFrame()

ranking_SWING_crand_mean = pd.DataFrame()
ranking_dynGENIE3_crand_mean = pd.DataFrame()

ranking_SWING = pd.read_csv(f"C:/Users/ivana/OneDrive/Desktop/Internship New Folder/Analysis Experimental Data/Results_instances-1000/Results_SWING_{experiment_ID}_genes-157/Mean_Importance_{experiment_ID}/ranking_SWING_{experiment_ID}_range{first}-{end}.txt", sep = "\t").sort_values(by=["regulator-target"])

ranking_SWING_mean["regulator-target"] = genes_name["regulator-target_names"].values.tolist()
ranking_dynGENIE3_mean["regulator-target"] = genes_name["regulator-target_names"].values.tolist()

ranking_SWING_rand_mean["regulator-target"] = genes_name["regulator-target_names"].values.tolist()
ranking_dynGENIE3_rand_mean["regulator-target"] = genes_name["regulator-target_names"].values.tolist()

ranking_SWING_crand_mean["regulator-target"] = genes_name["regulator-target_names"].values.tolist()
ranking_dynGENIE3_crand_mean["regulator-target"] = genes_name["regulator-target_names"].values.tolist()

ranking_SWING_mean["mean"] = ranking_SWING_DataFrame.mean(axis = 1)
ranking_dynGENIE3_mean["mean"] = ranking_dynGENIE3_DataFrame.mean(axis = 1)

ranking_SWING_rand_mean["mean"] = ranking_SWING_rand_DataFrame.mean(axis = 1)
ranking_dynGENIE3_rand_mean["mean"] = ranking_dynGENIE3_rand_DataFrame.mean(axis = 1)

ranking_SWING_crand_mean["mean"] = ranking_SWING_crand_DataFrame.mean(axis = 1)
ranking_dynGENIE3_crand_mean["mean"] = ranking_dynGENIE3_crand_DataFrame.mean(axis = 1)

ranking_SWING_mean = ranking_SWING_mean.sort_values(by = ["mean"], ascending = False)
ranking_dynGENIE3_mean = ranking_dynGENIE3_mean.sort_values(by = ["mean"], ascending = False)

ranking_SWING_rand_mean = ranking_SWING_rand_mean.sort_values(by = ["mean"], ascending = False)
ranking_dynGENIE3_rand_mean = ranking_dynGENIE3_rand_mean.sort_values(by = ["mean"], ascending = False)

ranking_SWING_crand_mean = ranking_SWING_crand_mean.sort_values(by = ["mean"], ascending = False)
ranking_dynGENIE3_crand_mean = ranking_dynGENIE3_crand_mean.sort_values(by = ["mean"], ascending = False)

# SWING

In [3]:
# Regulator
m = ranking_SWING_mean["regulator-target"].values.tolist()

Interaction_regulator = pd.DataFrame()
Position_regulator = pd.DataFrame()

for noncoding in noncoding_genes:
    
    list_noncoding = [re.search(f"('{noncoding}','(.+?)')", m[i]) for i in range(len(m))]
    list_noncoding_ = [list_noncoding[i].group(1) for i in range(len(list_noncoding)) if list_noncoding[i] != None]
    list_index = [i for i in range(len(list_noncoding)) if list_noncoding[i] != None]
    Interaction_regulator[f"{noncoding}"] = [list_noncoding_[0]]
    Position_regulator[f"{noncoding}"] = [list_index[0]]

In [4]:
Interaction_regulator

,ASCO,APOLO,MARS,LCA,LAM,BRO,BAP,CAL,PYKA,ABRA,SF23,CYCA
0,"'ASCO','ATHD2A'","'APOLO','ARF18'","'MARS','CUC3'","'LCA','APOLO'","'LAM','APOLO'","'BRO','EGL3'","'BAP','ARF1'","'CAL','PLT7'","'PYKA','KAN4'","'ABRA','KAN4'","'SF23','DPA'","'CYCA','ARF16'"

In [5]:
Position_regulator

   ASCO  APOLO  MARS   LCA   LAM  BRO   BAP   CAL  PYKA  ABRA  SF23  CYCA
0     1   2473  1465  1742  4345   73  2800  3008  1665  1897    96   531

In [6]:
Interaction_target = pd.DataFrame()
Position_target = pd.DataFrame()

for noncoding in noncoding_genes:
    
    list_noncoding = [re.search(f"('(.+?)','{noncoding}')", m[i]) for i in range(len(m))]
    list_noncoding_ = [list_noncoding[i].group(1) for i in range(len(list_noncoding)) if list_noncoding[i] != None]
    list_index = [i for i in range(len(list_noncoding)) if list_noncoding[i] != None]
    Interaction_target[f"{noncoding}"] = [list_noncoding_[0]]
    Position_target[f"{noncoding}"] = [list_index[0]]

In [7]:
Interaction_target

,ASCO,APOLO,MARS,LCA,LAM,BRO,BAP,CAL,PYKA,ABRA,SF23,CYCA
0,"'ANT','ASCO'","'LCA','APOLO'","'AL1','MARS'","'E2FA','LCA'","'IAA11','LAM'","'bZIP8','BRO'","'CLV2','BAP'","'ANT','CAL'","'GATA23','PYKA'","'ARF4','ABRA'","'LCA','SF23'","'WKRY56','CYCA'"

In [8]:
Position_target

   ASCO  APOLO  MARS  LCA   LAM  BRO   BAP  CAL  PYKA  ABRA  SF23  CYCA
0  2497   1742  1639  470  1079  394  3709  820  5189   378  2387  1458

# dynGENIE3

In [8]:
# Regulator
m = ranking_dynGENIE3_mean["regulator-target"].values.tolist()

Interaction_regulator = pd.DataFrame()
Position_regulator = pd.DataFrame()

for noncoding in noncoding_genes:
    
    list_noncoding = [re.search(f"('{noncoding}','(.+?)')", m[i]) for i in range(len(m))]
    list_noncoding_ = [list_noncoding[i].group(1) for i in range(len(list_noncoding)) if list_noncoding[i] != None]
    list_index = [i for i in range(len(list_noncoding)) if list_noncoding[i] != None]
    Interaction_regulator[f"{noncoding}"] = [list_noncoding_[0]]
    Position_regulator[f"{noncoding}"] = [list_index[0]]

Interaction_target = pd.DataFrame()
Position_target = pd.DataFrame()

for noncoding in noncoding_genes:
    
    list_noncoding = [re.search(f"('(.+?)','{noncoding}')", m[i]) for i in range(len(m))]
    list_noncoding_ = [list_noncoding[i].group(1) for i in range(len(list_noncoding)) if list_noncoding[i] != None]
    list_index = [i for i in range(len(list_noncoding)) if list_noncoding[i] != None]
    Interaction_target[f"{noncoding}"] = [list_noncoding_[0]]
    Position_target[f"{noncoding}"] = [list_index[0]]

In [9]:
Interaction_regulator

,ASCO,APOLO,MARS,LCA,LAM,BRO,BAP,CAL,PYKA,ABRA,SF23,CYCA
0,"'ASCO','ABRA'","'APOLO','REV'","'MARS','GH3.17'","'LCA','SHR'","'LAM','LHW'","'BRO','CNA'","'BAP','MEL2'","'CAL','CNA'","'PYKA','BBM'","'ABRA','ARF6'","'SF23','CDKB2;1'","'CYCA','BRO'"

In [10]:
Position_regulator

   ASCO  APOLO  MARS  LCA  LAM  BRO  BAP  CAL  PYKA  ABRA  SF23  CYCA
0    24    717   443  650  179   13   47   28  1327    69   225   146

In [11]:
Interaction_target

,ASCO,APOLO,MARS,LCA,LAM,BRO,BAP,CAL,PYKA,ABRA,SF23,CYCA
0,"'PID','ASCO'","'ARF1','APOLO'","'BDL','MARS'","'PGP4','LCA'","'ORTH1','LAM'","'BDL','BRO'","'AHP6','BAP'","'CYCD2;1','CAL'","'GCN5','PYKA'","'ARF4','ABRA'","'PHV','SF23'","'MGP','CYCA'"

In [12]:
Position_target

   ASCO  APOLO  MARS  LCA  LAM  BRO  BAP  CAL  PYKA  ABRA  SF23  CYCA
0   308   2228   601  685   34  109  155  480   495    15   261   902